### PR TITLE
Update osx cookbook location to allow chef to run

### PR DESCRIPTION
**Pull request by wendorf**

### CODE REVIEW

**Comment by hiremaga** [comment]
@codeword @wendorf looks like we might also need an updated url for keycastr. cheffiles.pivotallabs.com is no longer online. 

This means this cookbook has probably been broken for a few months and nobody has noticed. Makes me question the value of continuing to maintain it.

**Comment by aramprice** [comment]
Looks like brew has this now, I recommend we kill this cookbook:

```
brew cask search keycastr
==> Exact match
keycastr
```

**Comment by wendorf** [comment]
Just tested installing it via cask, and it has pretty sane defaults. Everything we have recipes for is configurable via the UI. It wouldn't be too hard to maintain this cookbook, but I agree that the value is pretty low.

**Comment by wendorf** [comment]
This cookbook has been deprecated. Closing this PR.

**Pull request closed without merging**
